volumes:
  mealie-data:                                  # Declares a named volume for persisting application data.

networks:
  zabbix-network:
    driver: bridge
services:
  duplicati:
    image: duplicati/duplicati:2.1.1.0
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_duplicati
    hostname: duplicati
    restart: unless-stopped
    # Recommendation: Duplicati needs root user to get access to all files
    user: "${DOCKER_ROOTPUID:-0}:${DOCKER_ROOTPGID:-0}"
    network_mode: bridge
    ports:
      - 8200:8200
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/duplicati_data:/data:rw
      - /docker/backups:/backups:rw
      - ${DOCKER_PATH_PERSISTENT}:/source:ro
      - ${CONFIG_PATH}:/config:ro      
    environment:
      - TZ=${DOCKER_TZ}

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${BOT_TOKEN}@telegram/?channels=${CHAT_ID}

  dozzle:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_dozzle
    image: amir20/dozzle:v8.13.8
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=10.0.0.105  # replace with your actual Zabbix server hostname or IP
      - ZBX_HOSTNAME=zabbix-mealie
    networks:
      - zabbix-network
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # glances:
  #   container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_glances
  #   image: nicolargo/glances:4.3.1
  #   restart: unless-stopped
  #   pid: host
  #   ports:
  #     - 61208:61208
  #   command: ["glances", "-w"]
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /var/docker/glances:/glances/conf


  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0             # Specifies the Mealie Docker image and version.
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_mealie  # Names the container for easier management.
    restart: unless-stopped
    ports:
      - 9000:9000                                           # Maps port 9925 on the host to port 9000 in the container.
    deploy:
      resources:
        limits:
          memory: 1000M                         # Limits the container to use a maximum of 1000M of memory.
    volumes:
      - mealie-data:/app/data/                  # Persists data in a named volume.
    environment:
      - ALLOW_SIGNUP=true                       # Allows new user signups on the Mealie instance.
      - PUID=1000                               # Sets the user ID for the container.
      - PGID=1000                               # Sets the group ID for the container.
      - TZ=${DOCKER_TZ}                         # Sets the timezone for the container.
      - MAX_WORKERS=1                           # Limits the number of workers to 1.
      - WEB_CONCURRENCY=1                       # Sets the concurrency level for web workers.
      - BASE_URL=https://mealie.turel.cloud     # The base URL where Mealie is accessed.
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_EMAIL=cyturel@gmail.com
      - SMTP_USER=cyturel@gmail.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}


