version: "3.3"

services:
  watchtower:
    image: containrrr/watchtower:1.5.1
    container_name: custom_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=ha@turkel.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=cyturel@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=cyturel@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}
       
  plex:
    image: linuxserver/plex:1.29.2
    container_name: custom_plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /home/home/hassio/plex/config:/config
      - /home/home/hassio/transmission/downloads/complete:/tv
      - /home/home/hassio/plex/movies:/movies
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:version-3.00-r5
    container_name: custom_transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=ha #optional
      - PASS=tv #optional
    volumes:
      - /home/home/hassio/transmission/config:/config
      - /home/home/hassio/transmission/downloads:/downloads
      - /home/home/hassio/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/home/hassio/sonarr/config:/config
      - /home/home/hassio/sonarr/downloads:/downloads
      - /home/home/hassio/sonarr/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped


