version: "3.3"

services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_duplicati
    hostname: duplicati
    restart: always
    # Recommendation: Duplicati needs root user to get access to all files
    user: "${DOCKER_ROOTPUID:-0}:${DOCKER_ROOTPGID:-0}"
    network_mode: bridge
    ports:
      - 8200:8200
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/duplicati_data:/data:rw
      - /docker/backups:/backups:rw
      - ${DOCKER_PATH_PERSISTENT}:/source:ro
    environment:
      - TZ=${DOCKER_TZ}

  watchtower:
    image: containrrr/watchtower:1.5.3
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${BOT_TOKEN}@telegram/?channels=${CHAT_ID}

  dozzle:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_dozzle
    image: amir20/dozzle:v4.10.24
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  swag:
    image: ghcr.io/linuxserver/swag:1.32.0
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - URL=turkel.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - EMAIL=cyturel@gmail.com
      - ONLY_SUBDOMAINS=false
      - STAGING=false
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  authelia:
    image: authelia/authelia:4.37.5
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    ports:
      - 9092:9091
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/authelia:/config
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_redis
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
      - PUID=1000
      - PGID=1000

  heimdall:
    image: linuxserver/heimdall:2.5.6
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/heimdall:/config
    ports:
      - 8070:80

  glances:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}_glances
    image: docker.io/nicolargo/glances
    restart: always
    network_mode: host
    ports:
      - 61208:61208
    command: ["glances", "-w"]
