- Developer:
    - GitHub:
        - icon: si-github
          href: https://github.com

- Social:
    - Facebook:
        - icon: si-facebook
          href: https://facebook.com
    - LinkedIn:
        - icon: si-linkedin
          href: https://linkedin.com
    - X:
        - icon: si-x
          href: https://x.com
    - Reddit:
        - icon: si-reddit
          href: https://reddit.com

- Entertainment:
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com
