- Developer:
    - GitHub:
        - icon: si-github
          href: https://github.com/chaimt

- Social:
    - Facebook:
        - icon: si-facebook
          href: https://facebook.com
    - LinkedIn:
        - icon: si-linkedin
          href: https://www.linkedin.com/in/chaim-turkel/
    - X:
        - icon: si-x
          href: https://x.com/chaimt
    - Reddit:
        - icon: si-reddit
          href: https://reddit.com

- Entertainment:
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com
