- Developer:
    - GitHub:
        - icon: si-github
          href: https://github.com

- Social:
    - Reddit:
        - icon: si-reddit
          href: https://reddit.com

- Entertainment:
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com
