- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    network: true

- openmeteo:
    label: Home
    latitude: 32.1184749    
    longitude: 35.1301673
    units: metric
    cache: 5
