- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23

- openmeteo:
    label: Home
    latitude: 32.06663020
    longitude: 34.781599
    units: metric
    cache: 5
